---
- name: Create Google Cloud VM for All In One
  hosts: all
  gather_facts: no
  vars_files:
    - dev_env.yml
    # 请参考项目中的 vm_instances.yml 文件
    # - vm_instances.yml

  tasks:
    - name: Activate service account
      shell: gcloud auth activate-service-account --key-file=/path/to/your/service-account-file.json

    - name: Create static IP addresses
      shell: >
        gcloud compute addresses create ip-{{ item.host_name }}
        --project={{ PROJECT_ID }}
        --region={{ item.zone | regex_replace("-[^-]*$","") }}
      with_items: "{{ vm_instances }}"
      failed_when: false

    - name: Get static IP addresses
      shell: >
        gcloud compute addresses describe ip-{{ item.host_name }}
        --project={{ PROJECT_ID }}
        --region={{ item.zone | regex_replace("-[^-]*$","")}}
        --format="get(address)"
      with_items: "{{ vm_instances }}"
      register: static_ip_addresses
      changed_when: false

    # - debug:
    #     var: static_ip_addresses

    - name: Create VM instances
      shell: >
        gcloud compute instances create {{ item.item.host_name }}
        --project={{ PROJECT_ID }}
        --zone={{ item.item.zone }}
        --machine-type={{ item.item.machine_type }}
        --network-interface=network-tier=PREMIUM,stack-type=IPV4_ONLY,subnet=default,address={{ item.stdout }}
        --maintenance-policy=MIGRATE
        --provisioning-model=STANDARD
        --service-account={{ GOOGLE_SERVICE_ACCOUNT }}
        --scopes=https://www.googleapis.com/auth/cloud-platform
        --min-cpu-platform=Automatic
        --tags={{ item.item.host_name.split('-')[0] }},http-server,https-server
        --no-shielded-secure-boot
        --shielded-vtpm
        --shielded-integrity-monitoring
        --labels=goog-ops-agent-policy=v2-x86-template-1-2-0,goog-ec-src=vm_add
        --reservation-affinity=any
        --source-machine-image=debian11-erlang
      with_items: "{{ static_ip_addresses.results }}"
      register: instance_creation_results

    - debug:
        var: instance_creation_results

