---
- name: Deploy and execute tasks on remote hosts
  hosts: all
  become: true
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Copy all files from local ./config directory to the remote home directory
      copy:
        src: "./config/"
        dest: "~/"
        mode: preserve

    - name: Download m1x project
      command: gsutil cp gs://matr1x-fire-server-pkg/m1x-awx-deploy.tar.gz ./m1x.tar.gz 
      args:
        chdir: "~/"

    - name: Create m1x directory if not exist
      ansible.builtin.file:
        path: "~/m1x"
        state: directory

    - name: Remove existing files in m1x directory
      ansible.builtin.file:
        path: "~/m1x/*"
        state: absent

    - name: Unpack m1x.tar.gz
      ansible.builtin.shell:
        cmd: "tar -xz -f ~/m1x.tar.gz -C ~/m1x"

    - name: Download and Install Docker Compose
      become: true
      shell: |
        curl -L "https://github.com/docker/compose/releases/download/v2.24.5/docker-compose-linux-x86_64" -o /usr/local/bin/docker-compose
        chmod +x /usr/local/bin/docker-compose
    
    - name: Install docker.io for Debian/Ubuntu
      ansible.builtin.apt:
        name: docker.io
        state: present
        update_cache: yes

    - name: Install pip3 for Debian/Ubuntu
      ansible.builtin.apt:
        name: python3-pip
        state: present
        update_cache: yes

    - name: install Docker SDK for Python
      ansible.builtin.pip:
        name: docker
        executable: pip3
      vars:
        ansible_python_interpreter: /usr/bin/python3

    - name: Log in to Docker Hub
      community.docker.docker_login:
        username: khalilwang
        password: asdqwe!234

    - name: Execute docker-compose up -d
      command: docker-compose up -d
      args:
        chdir: "~/"