---
- name: Down all-in-one
  hosts: all
  become: true
  become_user: root
  become_method: sudo su -
  vars:
    ansible_python_interpreter: /usr/bin/python3

  tasks:
    - name: Execute docker-compose down
      community.docker.docker_compose:
        project_src: ~/
        env_file: config/env.yml
        state: absent