logging:
  receivers:
    app_file_logging:
      type: files
      include_paths: [/home/tom/data/*.md, /root/data/*/*.md]
      record_log_file_path: true

    app_tcp_logging:
      type: tcp
      format: json
      listen_host: 0.0.0.0
      listen_port: 5171

  service:
    pipelines:
      default_pipeline:
        receivers: [syslog, app_file_logging, app_tcp_logging]